name: Build Python
on:
  push:
    branches:
      - main
jobs:
  bulid-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # bootstrap.py calls msbuild
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Bootstrap
        working-directory: python
        run: python3 bootstrap.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run python pyrgbd/_build_librgbd_ffi.py

      - name: Test
        working-directory: python
        run: poetry run python test_encoder.py

  bulid-mac:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ninja

      - name: Bootstrap
        working-directory: python
        run: python3 bootstrap.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run python pyrgbd/_build_librgbd_ffi.py

      - name: Test
        working-directory: python
        run: poetry run python test_encoder.py


  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get -y install ninja-build

      - name: Bootstrap
        working-directory: python
        run: python3 bootstrap.py

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run python pyrgbd/_build_librgbd_ffi.py

      - name: Test
        working-directory: python
        run: poetry run python test_encoder.py
