name: Build
on:
  push:
    branches:
      - main
jobs:
  bulid-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: cmake
        run: cmake -B build
      - name: make
        run: (cd build; make -j2)