name: Build
on:
  push:
    branches:
      - main
jobs:
  bulid-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ../

      - name: Build
        run: |
          cd build
          make -j2

  bulid-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ../

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: |
          cd build
          msbuild librgbd.sln -verbosity:diag -property:Configuration=Release
